config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users
  resources :cartitems
  resources :orders
  resources :orderitems, only: :update
  resources :search, only: :index
  resources :subcategories, only: :show
  resources :products, only: :show
  resources :rates, only: [:create, :update]
  resources :comments
  resources :suggests

  namespace :admin do
    root "admin#index"
    resources :users, except: [:show, :new, :create]
    resources :categories
    resources :subcategories, except: [:show]
    resources :products
    resources :orders
    resources :orderitems
    resources :suggests
    resources :statistics, only: :index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    check_params params[:input_search], params[:input_min], params[:input_max]
  end

  private

  def check_params search, min, max
    case
    when search.present? && min.blank? && max.blank?
      @products = Product.search_name(search).list_products_desc.
        paginate page: params[:page], per_page: Settings.per_page
    when (search.present? || search.blank?) && min.blank? && max.present?
      @products = Product.search_name(search).max_price(max).
        list_products_desc.paginate page: params[:page],
        per_page: Settings.per_page
    when (search.present? || search.blank?) && max.blank? && min.present?
      @products = Product.search_name(search).min_price(min).
        list_products_desc.paginate page: params[:page],
        per_page: Settings.per_page
    when search.blank? && min.present? && max.present?
      @products = Product.min_price(min).max_price(max).
        list_products_desc.paginate page: params[:page],
        per_page: Settings.per_page
    when search.blank? && min.blank? && max.blank?
      @products = Product.search_name(search).list_products_desc.
        paginate page: params[:page],
        per_page: Settings.per_page
    else
      @products = Product.search_name(search).min_price(min).
        max_price(max).list_products_desc.paginate page: params[:page],
        per_page: Settings.per_page
    end
  end
end

app/views/search/index.html.erb
<% provide :title, t("view.search.title") %>
<h3 class="text-center"><%= t "view.search.header" %></h3>

<div class=row>
  <div class="col-md-4 col-md-offset-4">
    <%= form_tag search_index_path, class: "form-search-detail", method: :get do %>
      <label><%= t "key_word" %></label>
      <%= text_field_tag :input_search, params[:input_search],
        class: "form-control" %>
      <label><%= t "view.min" %></label>
      <%= text_field_tag :input_min, params[:input_min],
        class: "form-control", required: true %>
      <label><%= t "view.max" %></label>
      <%= text_field_tag :input_max, params[:input_max],
        class: "form-control", required: true %>
      <label class="label-form"><%= t "find_by" %></label>
      <%= select_tag :find_by, options_for_select([[t("view.search.find_by.name")],
        [t("view.search.find_by.rate")]]), class: "form-control select-form" %>
      <hr>
      <%= submit_tag t("view.search.btn_search"), name: nil,
        class: "btn btn-success col-md-4 col-md-offset-4" %>
    <% end %>
  </div>
</div>

<hr>

<div class="row">
  <%= render partial: "static_pages/list_products", collection: @products,
    as: :product %>
</div>
<%= will_paginate @products %>