config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users
  resources :cartitems
  resources :orders
  resources :orderitems, only: :update
  resources :search, only: :index
  resources :subcategories, only: :show
  resources :products, only: :show
  resources :rates, only: [:create, :update]
  resources :comments
  resources :suggests

  namespace :admin do
    root "admin#index"
    resources :users, except: [:show, :new, :create]
    resources :categories
    resources :subcategories, except: [:show]
    resources :products
    resources :orders
    resources :orderitems
    resources :suggests
    resources :statistics, only: :index
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :orderitems, dependent: :destroy

  enum status: {pending: 1, accepted: 2, reject: 3}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum: Settings.maximum_name}
  validates :email, presence: true, length: {maximum: Settings.maximum_name_email},
    format: {with: VALID_EMAIL_REGEX}
  validates :address, presence: true, length: {maximum: Settings.maximum_address}
  validates :phone, presence: true, numericality: {only_integer: true},
    length: {in: Settings.min_range_phone..Settings.max_range_phone}
  validates :user_id, presence: true

  scope :newest, ->{order created_at: :desc}
  scope :this_month, -> do
    where("created_at >= ? AND created_at <= ?",
    Time.now.beginning_of_month, Time.now.end_of_month)
  end
  scope :last_month, -> do
    where("created_at >= ? AND created_at <= ?",
    Settings.one_month_ago.month.ago.beginning_of_month,
    Settings.one_month_ago.month.ago.end_of_month)
  end
  scope :two_month_ago, -> do where("created_at >= ? AND created_at <= ?",
    Settings.two_month_ago.month.ago.beginning_of_month,
    Settings.two_month_ago.month.ago.end_of_month)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :verify_admin?
  before_action :load_order, except: [:index, :new, :create]

  def index
    @orders = Order.newest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
    @orderitems = @order.orderitems.newest.paginate page: params[:page],
      per_page: Settings.per_page
    return if @orderitems
    flash[:warning] = t "view.admin.orderitems.not_found"
    redirect_to admin_orders_path
  end

  def edit
  end

  def update
    if @order.update_attributes order_params
      flash[:success] = t "view.admin.orders.update.success_msg"
      redirect_to admin_orders_path
    else
      render :edit
    end
  end

  def destroy
    if @order.destroy
      flash[:success] = t "view.admin.orders.destroy.success_msg"
    else
      flash[:danger] = t "view.admin.orders.destroy.error_msg"
    end
    redirect_to admin_orders_path
  end

  private

  def order_params
    params.require(:order).permit :name,
      :user_id, :address, :phone, :status, :total
  end

  def load_order
    @order = Order.find_by id: params[:id]
    return if @order
    flash[:warning] = t "view.admin.orders.not_found"
    redirect_to admin_orders_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_order_user, only: [:edit, :update]
  before_action :create_cart
  before_action :check_cart, only: [:new, :create]
  before_action :load_cart, only: [:new, :create]
  before_action :load_order, only: [:show, :edit, :update]
  before_action :check_status, only: [:edit, :update]

  def index
    @orders = current_user.orders.newest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def new
    @order = Order.new
  end

  def show
    @orderitems = @order.orderitems.newest.paginate page: params[:page],
      per_page: Settings.per_page
    return if @orderitems
    flash[:warning] = t "view.orderitems.not_found"
    redirect_to orders_path
  end

  def create
    @order = current_user.orders.new order_params
    @order.transaction do
      if @order.save!
        @cartitems.each do |key, value|
          @orderitem = @order.orderitems.new product_id: key, quantity: value
          @orderitem.transaction do
            raise t "view.orders.create.trans_fail" unless @orderitem.save!
          end
        end
        UserMailer.order_mail(current_user, @order).deliver_now
        flash[:success] = t "view.orders.create.success_msg"
        redirect_to root_path
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    if params[:status].to_i == Settings.reject_order
      if @order.update_attributes status: params[:status].to_i
        flash[:success] = t "view.orders.update.reject_ok"
      else
        flash[:danger] = t "view.orders.update.reject_fail"
      end
      redirect_to orders_path
    else
      if @order.update_attributes order_params
        flash[:success] = t "view.orders.update.success_msg"
        redirect_to @order
      else
        render :edit
      end
    end
  end

  private

  def order_params
    params.require(:order).permit :name, :email, :address, :phone, :total
  end

  def load_cart
    @cartitems = session[:cart]
  end

  def load_order
    @order = current_user.orders.find_by id: params[:id]
    return if @order
    flash[:warning] = t "view.orders.not_found"
    redirect_to orders_path
  end

  def check_status
    return if @order.pending?
    flash[:warning] = t "view.orders.status_msg"
    redirect_to orders_path
  end
end

app/views/admin/orders/_form.html.erb
<%= form_for [:admin, @order] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/orders/edit.html.erb
<% provide :title, t("view.admin.orders.edit.title") %>
<% provide :button_text, t("view.admin.orders.edit.btn_update") %>

<h1><%= t "view.admin.orders.edit.header" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<% provide :title, t("view.admin.orders.index.title") %>
<h1><%= t "view.admin.orders.index.header" %></h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th><%= t "view.admin.orders.index.table_th.order_number" %></th>
      <th><%= t "view.admin.orders.index.table_th.name" %></th>
      <td><%= t "view.admin.orders.index.table_th.address" %></td>
      <td><%= t "view.admin.orders.index.table_th.phone" %></td>
      <td><%= t "view.admin.orders.index.table_th.total" %></td>
      <td><%= t "view.admin.orders.index.table_th.time" %></td>
      <td><%= t "view.status" %></td>
      <td><%= t "view.view" %></td>
      <th><%= t "view.edit" %></th>
      <th><%= t "view.delete" %></th>
    </tr>
  </thead>
    <tbody>
    <% @orders.each_with_index do |order, index| %>
      <tr>
        <td><%= count_index index %></td>
        <td><%= link_to order.name, admin_order_path(order) %></td>
        <td><%= order.address %></td>
        <td><%= order.phone %></td>
        <td><%= order.total %></td>
        <td>
          <%= (time_ago_in_words order.created_at) << t("view.ago") %>
        </td>
        <td><%= order.status %></td>
        <td><%= link_to t("view.view"),admin_order_path(order),
          class: "btn btn-info" %>
        </td>
        <td><%= link_to t("view.edit"),
          edit_admin_order_path(order), class: "btn btn-success" %>
        </td>
        <td>
        <%= link_to t("view.delete"),
          admin_order_path(order), method: :delete, class: "btn btn-danger",
          data: {confirm: t("view.sure?")} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @orders %>

app/views/admin/orders/show.html.erb
<% provide :title, t("view.admin.categories.index.title") %>
<h1><%= t "view.admin.orders.show.header" %> <%= @order.name %></h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th><%= t "view.admin.orders.index.table_th.order_number" %></th>
      <th><%= t "view.admin.orders.index.table_th.product_name" %> </th>
      <th><%= t "view.admin.orders.index.table_th.quantity" %></th>
      <th><%= t "view.admin.orders.index.table_th.status" %></th>
      <th><%= t "view.admin.orders.index.table_th.time" %></th>
      <% if @order.pending? %>
        <th><%= t "view.admin.orders.index.table_th.change_status" %></th>
      <% end %>
    </tr>
  </thead>
    <tbody>
    <% @orderitems.each_with_index do |orderitem, index| %>
      <tr>
        <td><%= count_index index %></td>
        <td><%= orderitem.product_name %></td>
        <td><%= orderitem.quantity %></td>
        <td>
          <span class="status label label-<%= orderitem.status ? "success" : "danger" %>">
            <%= orderitem.status ? t("view.placed") : t("view.cancel") %>
          </span>
        </td>
        <td>
          <%= (time_ago_in_words orderitem.created_at) << t("view.ago") %>
        </td>
        <% if @order.pending? %>
          <th>
            <button id="<%= orderitem.id %>" data-status="<%= !orderitem.status %>"
              class="btn btn-info change-status">
              <%= t "view.admin.orders.index.table_th.change" %>
            </button>
          </th>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>