config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users
  resources :cartitems
  resources :orders
  resources :orderitems, only: :update
  resources :search, only: :index
  resources :subcategories, only: :show
  resources :products, only: :show
  resources :rates, only: [:create, :update]
  resources :comments
  resources :suggests

  namespace :admin do
    root "admin#index"
    resources :users, except: [:show, :new, :create]
    resources :categories
    resources :subcategories, except: [:show]
    resources :products
    resources :orders
    resources :orderitems
    resources :suggests
    resources :statistics, only: :index
  end
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  belongs_to :user
  belongs_to :subcategory

  enum status: {pending: 1, accepted: 2, reject: 3}

  validates :name, presence: true, length: {maximum: Settings.max_name_suggest}
  validates :subcategory_id, presence: true

  delegate :name, to: :subcategory, prefix: true

  scope :newest, ->{order created_at: :desc}
end

app/controllers/admin/suggests_controller.rb
class Admin::SuggestsController < ApplicationController
  before_action :verify_admin?
  before_action :load_suggest, only: [:edit, :update]

  def index
    @suggests = current_user.suggests.newest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def edit
  end

  def update
    if @suggest.update_attributes suggest_params
      flash[:success] = t "view.admin.suggests.update.success_msg"
      redirect_to suggests_path
    else
      render :edit
    end
  end

  private

  def load_subcategories
    @subcategories = Subcategory.all
    return if @subcategories
    flash[:warning] = t "view.admin.suggests.not_found"
    redirect_to root_path
  end

  def suggest_params
    params.require(:suggest).permit :status
  end

  def load_suggest
    @suggest = Suggest.find_by id: params[:id]
    return if @suggest
    flash[:warning] = t "view.admin.suggests.not_found_suggest"
    redirect_to :back
  end
end

app/controllers/suggests_controller.rb
class SuggestsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_suggest_user, only: [:edit, :update, :destroy]
  before_action :load_suggest, only: [:edit, :update, :destroy]
  before_action :check_status, only: [:edit, :update, :destroy]
  before_action :load_subcategories, only: [:new, :edit, :update]

  def index
    @suggests = current_user.suggests.newest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def new
    @suggest = Suggest.new
  end

  def create
    @suggest = current_user.suggests.new suggest_params
    if @suggest.save
      flash[:success] = t "view.suggests.create.success_msg"
      redirect_to suggests_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @suggest.update_attributes suggest_params
      flash[:success] = t "view.suggests.update.success_msg"
      redirect_to suggests_path
    else
      render :edit
    end
  end

  def destroy
    if @suggest.destroy
      flash[:success] = t "view.suggests.destroy.success_msg"
    else
      flash[:danger] = t "view.suggests.destroy.fail_msg"
    end
    redirect_to :back
  end

  private

  def load_subcategories
    @subcategories = Subcategory.all
    return if @subcategories
    flash[:warning] = t "view.suggests.not_found_sub"
    redirect_to root_path
  end

  def suggest_params
    params.require(:suggest).permit :name, :subcategory_id, :status
  end

  def check_status
    return if @suggest.pending?
    flash[:warning] = t "view.suggests.cant_modify"
    redirect_to suggests_path
  end

  def load_suggest
    @suggest = Suggest.find_by id: params[:id]
    return if @suggest
    flash[:warning] = t "view.suggests.not_found_suggest"
    redirect_to :back
  end
end

app/views/admin/suggests/_form.html.erb
<%= form_for @suggest do |suggest| %>
  <%= render "shared/error_messages", object: suggest.object %>

  <div class="form-group">
    <%= suggest.label :status %>
    <%= suggest.select :status,
      Suggest.statuses.keys.map{|status| [status.titleize, status]},
      {}, {class: "form-control"} %>
  </div>

  <%= suggest.submit yield(:button_text),
    class: "btn btn-primary col-md-4 col-md-offset-4" %>
<% end %>

app/views/admin/suggests/_list_suggests.html.erb
<tr>
  <td><%= suggest.name %></td>
  <td><%= suggest.subcategory_name %></td>
  <td>
    <%= (time_ago_in_words suggest.created_at) << t("view.ago") %>
  </td>
  <td><%= suggest.status %></td>
  <td>
    <%= link_to t("view.edit"), edit_admin_suggest_path(suggest), class: "btn btn-success" %>
  </td>
</tr>

app/views/admin/suggests/edit.html.erb
<% provide :title, t("view.admin.suggests.edit.title") %>
<% provide :button_text, t("view.admin.suggests.edit.btn_update") %>
<h1><%= t "view.admin.suggests.edit.header" %></h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= render "form" %>
  </div>
</div>

app/views/admin/suggests/index.html.erb
<% provide :title, t("view.admin.suggests.index.title") %>
<h1><%= t "view.admin.suggests.index.header" %></h1>

<% if @suggests.empty? %>
  <div class="alert alert-warning">
    <strong>
      <%= t("view.admin.suggests.index.not_found") %>
    </strong>
  </div>
<% else %>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th><%= t "view.admin.suggests.index.content" %></th>
        <td><%= t "view.admin.suggests.index.subcategory" %></td>
        <td><%= t "view.admin.suggests.index.time" %></td>
        <td><%= t "view.admin.suggests.index.status" %></td>
        <th><%= t "view.admin.suggests.index.edit" %></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "list_suggests", collection: @suggests, as: :suggest %>
    </tbody>
  </table>
  <%= will_paginate @suggests %>
<% end %>